# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_auto_20171122_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.Cluster', verbose_name='클러스터'),
        ),
    ]
