# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 15:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_auto_20171123_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(max_length=10, null=True, verbose_name='분류'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.Cluster', verbose_name='클러스터'),
        ),
        migrations.AlterField(
            model_name='article',
            name='writer',
            field=models.CharField(max_length=10, null=True, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.TextField(null=True, verbose_name='제보내용'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
