# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_auto_20171122_1353'),
        ('apiapp', '0007_merge_20171125_1100'),
    ]

    operations = [
    ]
