# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0009_auto_20171126_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='get_params',
            field=models.BooleanField(default=False, verbose_name='GET parameter 여부'),
            preserve_default=False,
        ),
    ]
