# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0010_media_get_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='get_params',
        ),
    ]
