# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0011_remove_media_get_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='mid',
            field=models.IntegerField(default=0, verbose_name='식별자'),
            preserve_default=False,
        ),
    ]
