# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0012_media_mid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.CharField(default='', max_length=10, verbose_name='토큰'),
        ),
    ]
